# Azure DevOps Pipeline for Node.js Express App
# Automatically builds, tests, and deploys to Azure Web App (Linux)
# Uses MongoDB Atlas & self-hosted agent 'kelompok3'

trigger:
- main

variables:
  # Azure Subscription ID (sesuaikan dengan milikmu)
  azureSubscription: '305f97ca-1ed0-4193-8619-c7ad1e9ad6ca'

  # Nama Web App di Azure
  webAppName: 'kel3'

  # Nama Environment di Azure
  environmentName: 'kel3'

  # MongoDB Connection String (gunakan secrets agar aman)
  mongoConnectionString: $(MONGO_CONNECTION_STRING)

  # Gunakan Self-Hosted Agent
  poolName: 'kelompok3'

stages:
- stage: Build
  displayName: 'Build & Test Stage'
  jobs:
  - job: Build
    displayName: 'Build & Test Job'
    pool:
      name: $(poolName)

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '22.x'
        displayName: 'Install Node.js 22.x'

      - script: |
          npm install
          npm run lint  # Linting untuk memastikan kode bersih
          npm run build --if-present
          npm run test --if-present
        displayName: 'Install Dependencies, Lint, Build, and Test'

      - task: ArchiveFiles@2
        displayName: 'Archive Build Artifacts'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false
          archiveType: zip
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true

      - publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        artifact: 'drop'

- stage: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: 'Deploy Job'
    environment: $(environmentName)
    pool:
      name: $(poolName)
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureWebApp@1
              displayName: 'Deploy to Azure Web App (Linux)'
              inputs:
                azureSubscription: $(azureSubscription)
                appType: 'webAppLinux'
                appName: $(webAppName)
                runtimeStack: 'NODE|22-lts'
                package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                startUpCommand: 'npm start'

            - script: |
                echo "Deployment successful to Azure!"
              displayName: 'Deployment Completed'
